-- ALTER statements generated (example). This file was generated as part of project migration support.
-- If your MySQL version does not support ADD COLUMN IF NOT EXISTS, remove IF NOT EXISTS and run carefully.

ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `id` BIGINT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `username` VARCHAR(255) NOT NULL UNIQUE;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `password_hash` VARCHAR(255) NOT NULL;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `birth_date` DATE NULL;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `height_cm` DECIMAL(5,2) NULL;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `sex` ENUM('male', 'female', 'other') NULL;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `activity_level` ENUM('low','medium','high') NULL;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `goals` ADD COLUMN IF NOT EXISTS `id` BIGINT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE `goals` ADD COLUMN IF NOT EXISTS `user_id` BIGINT NOT NULL;
ALTER TABLE `goals` ADD COLUMN IF NOT EXISTS `target_weight_kg` DECIMAL(5,2) NULL;
ALTER TABLE `goals` ADD COLUMN IF NOT EXISTS `target_bmi` DECIMAL(5,2) NULL;
ALTER TABLE `goals` ADD COLUMN IF NOT EXISTS `target_bmr` DECIMAL(7,2) NULL;
ALTER TABLE `goals` ADD COLUMN IF NOT EXISTS `target_tdee` DECIMAL(7,2) NULL;
ALTER TABLE `goals` ADD COLUMN IF NOT EXISTS `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `goals` ADD COLUMN IF NOT EXISTS `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `body_records` ADD COLUMN IF NOT EXISTS `id` BIGINT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE `body_records` ADD COLUMN IF NOT EXISTS `user_id` BIGINT NOT NULL;
ALTER TABLE `body_records` ADD COLUMN IF NOT EXISTS `record_date` DATE NOT NULL;
ALTER TABLE `body_records` ADD COLUMN IF NOT EXISTS `height_cm` DECIMAL(5,2) NOT NULL;
ALTER TABLE `body_records` ADD COLUMN IF NOT EXISTS `weight_kg` DECIMAL(5,2) NOT NULL;
ALTER TABLE `body_records` ADD COLUMN IF NOT EXISTS `bmi` DECIMAL(5,2) NOT NULL;
ALTER TABLE `body_records` ADD COLUMN IF NOT EXISTS `bmr` DECIMAL(7,2) NULL;
ALTER TABLE `body_records` ADD COLUMN IF NOT EXISTS `tdee` DECIMAL(7,2) NULL;
ALTER TABLE `body_records` ADD COLUMN IF NOT EXISTS `memo` TEXT NULL;
ALTER TABLE `body_records` ADD COLUMN IF NOT EXISTS `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `body_records` ADD COLUMN IF NOT EXISTS `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
